#!/usr/bin/env zsh

alias vi="vim"
alias vim="nvim"
alias vimdiff="vim -d"
alias o="open"
alias ofc="openFileContents"
alias vimrc="vim $HOME/.config/nvim/init.vim"
alias v="$EDITOR"

function leg {
  c "$HOME/data/college"*
}

function pro {
  c "$HOME/data/projetos"
}

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

unalias gb
